In [1]:
import numpy as np
import pandas as pd

# Datatype and Attributes
Numpy's main datatype is ndarray which refers to N-Dimensional Arrays

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

a3 = np.array([
               [[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]],
               [[19,20,21],
                [22,23,24],
                [25,26,28]]
              ])

In [5]:
a2.shape

(3, 3)

In [6]:
a3.shape

(3, 3, 3)

## Shape of the array
The shape of the array defines the number of axes the array has.
Shapes are quite useful while doing machine learning as the shape of the input dataframe should be equal to the output dataset. 
Arrays can be of any shape in Numpy

In [7]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [8]:
a1.size, a2.size, a3.size

(3, 9, 27)

### Creating a DataFrame from NumPy arrays

In [9]:
pd.DataFrame(a2)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

# Creating arrays

In [10]:
ones = np.ones([3,3], dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
zeros = np.zeros(3, dtype=int)
zeros

array([0, 0, 0])

In [12]:
range_array = np.arange(0,3,0.5, dtype=float)
range_array

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [13]:
random_array = np.random.randint(1,12,size=(3,5))
random_array

array([[ 5,  7,  1, 10,  7],
       [ 1,  7,  6, 10,  1],
       [ 8,  1,  2,  1,  9]])

In [14]:
random_array.size

15

In [15]:
random_array2 = np.random.random((3,5))
random_array2.shape

(3, 5)

In [16]:
random_array3 = np.random.rand(3,5)
random_array3.shape

(3, 5)

In [17]:
np.random.seed(seed=1)
random_array4 = np.random.randint(10,size=(2,3))
random_array4

array([[5, 8, 9],
       [5, 0, 0]])

# Viewing Arrays and Matrices

In [18]:
# Using np.unique() we can find unique numbers in an array
np.unique(random_array4)

array([0, 5, 8, 9])

## Manipulating and Comparing Arrays

### Arithmetic

In [19]:
a1

array([1, 2, 3])

In [20]:
ones = np.ones(3)

In [21]:
a1 + ones

array([2., 3., 4.])

In [22]:
a1 - ones

array([0., 1., 2.])

In [23]:
a1 * ones

array([1., 2., 3.])

In [24]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [45]:
a4 = np.ones((9,2),int)
a4

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [49]:
a2 = np.ones((2,3),int)
a3 = np.ones((2,3,3),int)
a3

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [55]:
a2.reshape(2,3,1) * a3

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])